@extends('marketing.layouts.default')

@section('content')

    @include('marketing.partials.breadcrumb-banner-mini')

    <div class="container">
        <div class="privacy-policy p-3">
            <p class="mb-4"><strong>Last updated:</strong> December 16, 2024</p>

            <p class="mb-5">
                This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use our Service. It also explains your privacy rights and how the law protects you.
            </p>

            <p class="mb-5">
                Millewwy International Enterprises Limited uses your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h3 class="mt-5 mb-4">Interpretation and Definitions</h3>
            <h4 class="mt-5 mb-3">Interpretation</h4>
            <p class="mb-5">
                Words with capitalized initial letters have meanings defined under the following conditions. These definitions apply whether they appear in singular or plural form.
            </p>

            <h4 class="mt-5 mb-3">Definitions</h4>
            <p class="mb-3">For the purposes of this Privacy Policy:</p>
            <ul class="mb-5">
                <li><strong>Account:</strong> A unique account created for you to access our Service or parts of our Service.</li>
                <li><strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party.</li>
                <li><strong>Company:</strong> Millewwy International Enterprises Limited, photo lab and printing press. 83 Opebi Rd, Opebi, Ikeja, Lagos, Nigeria.</li>
                <li><strong>Cookies:</strong> Small files placed on your device by a website, containing details of your browsing history.</li>
                <li><strong>Country:</strong> Nigeria</li>
                <li><strong>Device:</strong> Any device that can access the Service, such as a computer, cellphone, or tablet.</li>
                <li><strong>Personal Data:</strong> Information that relates to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> The Website.</li>
                <li><strong>Service Provider:</strong> Any person or company processing data on behalf of the Company.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or its infrastructure.</li>
                <li><strong>Website:</strong> indigoafrica.net</li>
                <li><strong>You:</strong> The individual accessing or using the Service, or the company/legal entity on whose behalf the Service is used.</li>
            </ul>

            <h3 class="mt-5 mb-4">Collecting and Using Your Personal Data</h3>
            <h4 class="mt-5 mb-3">Types of Data Collected</h4>
            <h5 class="mt-4 mb-2">Personal Data</h5>
            <p class="mb-3">
                While using our Service, we may ask you to provide certain personally identifiable information, including:
            </p>
            <ul class="mb-5">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
            </ul>

            <h5 class="mt-4 mb-2">Usage Data</h5>
            <p class="mb-3">
                Usage Data is collected automatically and may include your device's IP address, browser type and version, pages visited, time and date of visit, time spent on pages, device identifiers, and other diagnostic data.
            </p>
            <p class="mb-5">
                When accessing the Service via mobile device, we may collect information such as device type, unique ID, IP address, operating system, browser type, and other diagnostic data.
            </p>

            <h4 class="mt-5 mb-3">Tracking Technologies and Cookies</h4>
            <p class="mb-3">
                We use cookies and similar tracking technologies (beacons, tags, scripts) to track activity and store information. Technologies include:
            </p>
            <ul class="mb-5">
                <li><strong>Cookies or Browser Cookies:</strong> Small files placed on your device. You can refuse cookies via browser settings, but some Service features may not work.</li>
                <li><strong>Web Beacons:</strong> Small electronic files in our Service and emails to count users or gather statistics.</li>
            </ul>
            <p class="mb-3">
                Cookies can be "Persistent" (remain after you go offline) or "Session" (deleted when you close your browser).
            </p>
            <p class="mb-3">
                We use both types for purposes such as:
            </p>
            <ul class="mb-5">
                <li>
                    <strong>Necessary / Essential Cookies</strong> (Session): Enable core Service features and authenticate users.
                </li>
                <li>
                    <strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent): Identify if users have accepted cookies.
                </li>
                <li>
                    <strong>Functionality Cookies</strong> (Persistent): Remember choices you make, such as login details or language preference.
                </li>
            </ul>

            <h4 class="mt-5 mb-3">Use of Your Personal Data</h4>
            <p class="mb-3">The Company may use Personal Data for:</p>
            <ul class="mb-5">
                <li>Providing and maintaining our Service</li>
                <li>Managing your Account</li>
                <li>Fulfilling contracts</li>
                <li>Contacting you (email, phone, SMS, push notifications)</li>
                <li>Providing news, offers, and information about similar goods/services</li>
                <li>Managing your requests</li>
                <li>Business transfers (mergers, sales, etc.)</li>
                <li>Other purposes (analysis, trends, marketing, improvement)</li>
            </ul>
            <p class="mb-3">We may share your information:</p>
            <ul class="mb-5">
                <li>With Service Providers</li>
                <li>For business transfers</li>
                <li>With Affiliates</li>
                <li>With business partners</li>
                <li>With other users (public areas)</li>
                <li>With your consent</li>
            </ul>

            <h4 class="mt-5 mb-3">Retention of Your Personal Data</h4>
            <p class="mb-5">
                We retain Personal Data only as long as necessary for the purposes outlined in this Policy, to comply with legal obligations, resolve disputes, and enforce agreements. Usage Data is retained for a shorter period unless needed for security or functionality.
            </p>

            <h4 class="mt-5 mb-3">Transfer of Your Personal Data</h4>
            <p class="mb-5">
                Your information may be transferred to and maintained on computers outside your jurisdiction. By submitting information, you consent to this transfer. We ensure adequate controls and security for your data.
            </p>

            <h4 class="mt-5 mb-3">Delete Your Personal Data</h4>
            <p class="mb-5">
                You may request deletion of your Personal Data. You can update, amend, or delete your information via your Account settings or by contacting us. Some information may be retained as required by law.
            </p>

            <h4 class="mt-5 mb-3">Disclosure of Your Personal Data</h4>
            <h5 class="mt-4 mb-2">Business Transactions</h5>
            <p class="mb-5">
                If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will notify you before this occurs.
            </p>

            <h5 class="mt-4 mb-2">Law Enforcement</h5>
            <p class="mb-5">
                The Company may disclose your Personal Data if required by law or in response to valid requests by public authorities.
            </p>

            <h5 class="mt-4 mb-2">Other Legal Requirements</h5>
            <p class="mb-3">
                The Company may disclose your Personal Data to:
            </p>
            <ul class="mb-5">
                <li>Comply with legal obligations</li>
                <li>Protect rights or property</li>
                <li>Prevent or investigate wrongdoing</li>
                <li>Protect user or public safety</li>
                <li>Protect against legal liability</li>
            </ul>

            <h4 class="mt-5 mb-3">Security of Your Personal Data</h4>
            <p class="mb-5">
                We strive to protect your Personal Data, but no method of transmission or storage is 100% secure. We use commercially acceptable means but cannot guarantee absolute security.
            </p>

            <h4 class="mt-5 mb-3">Children's Privacy</h4>
            <p class="mb-5">
                Our Service does not address anyone under 13. We do not knowingly collect information from children under 13. If you believe your child has provided us with Personal Data, please contact us.
            </p>

            <h4 class="mt-5 mb-3">Links to Other Websites</h4>
            <p class="mb-5">
                Our Service may contain links to other websites. We are not responsible for their content or privacy practices. Please review their Privacy Policies.
            </p>

            <h4 class="mt-5 mb-3">Changes to this Privacy Policy</h4>
            <p class="mb-5">
                We may update this Privacy Policy. Changes will be posted on this page, and we may notify you via email or a prominent notice. Please review this Policy periodically.
            </p>

            <h4 class="mt-5 mb-3">Contact Us</h4>
            <p class="mb-3">
                If you have questions about this Privacy Policy, contact us:
            </p>
            <ul class="mb-5">
                <li>By phone: +234 809 876 0000</li>
            </ul>
        </div>
    </div>
    </div>

   
@endsection